version: 0.2

phases:
  install:
    commands:
      - echo installing node 13 ....
      - curl -sL https://deb.nodesource.com/setup_13.x |  bash -
      - apt install -y nodejs
      - echo installing npm...
      - curl -L https://npmjs.org/install.sh | sh
    pre-build:
      commands:
        - echo Installing dependencies
        - npm install
    build:
      commands:
        - echo building...
        - npm run webpack
        - npm run build
    artifacts:
      files:
        - "**/*"
      discard-paths: no
      base-directory: dist
