export const SET_PRODUCT_INFO = "SET_PRODUCT_INFO";
export const ADD_CART_ITEMS = "ADD_CART_ITEMS";
export const REMOVE_CART_ITEMS = "REMOVE_CART_ITEMS";
export const UPDATE_CART_ITEMS = "UPDATE_CART_ITEMS";
